### PR TITLE
Input optimization (4/4): Enter, Up, Down, and Backspace

### PR DESCRIPTION
**Pull request by maniacalhamster**
Used:
- indexing (by id) and splicing for data
- additional parameter (optional) and insertAdjacentHTML ('afterend') for display

Works for both top level bullets children bullets (had to change both `daily-log.js` and `bullet.js`)

As for the (1/4):
Maybe I'm ambitious but I also wanted to try to get:
- Tab: turn current bullet into last child of previous sibling
- Up/Down Arrow Keys: Visually move up and down 
  - Move up into last child if previous sibling has children
- Backspace: Auto focus into previous sibling after deletion
  - Move up into last child if previous sibling has children

### CODE REVIEW

**Review by asya-balas — APPROVED** [review]
woahhhh this is really nice

**Comment by maniacalhamster** [comment]
Edit: Me and Huy kept on it for the feature

Up/Down key implementation was difficult but we found some workarounds

Moving to prev bullet on backspace was pretty much copying the Up key implementation

Linter's JS Copy Paste Detector didn't like the code copying :0

**Comment by maniacalhamster** [comment]
Figured out tabbing, and then worked on cleaning up code - which went alright for `dialy-log.js` but it was a tad more difficult and messier in `bullet.js`

Please checkout (and pull) this branch and test it out as much as you can - want to 1000% make sure we know where the bugs are

**Comment by maniacalhamster** [comment]
Holy shit, the Linter accepted the changes - I have no clue how this code is "up to standard" but if it works it works :)

**Review by rshamoon — APPROVED** [review]

**Review by praneetbhoj — APPROVED** [review]

**Pull request merged**
